export enum ROLES {
  CEO = "CEO",
  ADMIN = "ADMIN",
  BAKER = "BAKER",
  DRIVER = "DRIVER",
  SUPPLIER = "SUPPLIER",
  DIVIDER = "DIVIDER",
  DIVIDER_TABLET = "DIVIDER_TABLET",
  BAKER_TABLET = "BAKER_TABLET",
  DOUGHMAKER = "DOUGHMAKER",
  DISPATCHER = "DISPATCHER",
  CLIENT = "CLIENT",
}
