export enum Status {
  READY = "READY",
  PROGRESS = "PROGRESS",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
  REDIRECTING = "REDIRECTING",
  DIVIDED = "DIVIDED",
  BAKED = "BAKED",
  SOLD = "SOLD",
}
